//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.488.0.
namespace Zool
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("failureType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FailureType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("message")]
        public string Message { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("stack-trace")]
        public string Stack_Trace { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("reasonType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReasonType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("message")]
        public string Message { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("resultsType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResultsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Test_SuiteType> _test_Suite;
        
        [System.Xml.Serialization.XmlElementAttribute("test-suite")]
        public System.Collections.ObjectModel.Collection<Test_SuiteType> Test_Suite
        {
            get
            {
                return this._test_Suite;
            }
            private set
            {
                this._test_Suite = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Test_Suite collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Test_SuiteSpecified
        {
            get
            {
                return (this.Test_Suite.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ResultsType" /> class.</para>
        /// </summary>
        public ResultsType()
        {
            this._test_Suite = new System.Collections.ObjectModel.Collection<Test_SuiteType>();
            this._test_Case = new System.Collections.ObjectModel.Collection<Test_CaseType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Test_CaseType> _test_Case;
        
        [System.Xml.Serialization.XmlElementAttribute("test-case")]
        public System.Collections.ObjectModel.Collection<Test_CaseType> Test_Case
        {
            get
            {
                return this._test_Case;
            }
            private set
            {
                this._test_Case = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Test_Case collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Test_CaseSpecified
        {
            get
            {
                return (this.Test_Case.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("test-suiteType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Test_SuiteType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CategoryType> _categories;
        
        [System.Xml.Serialization.XmlArrayAttribute("categories")]
        [System.Xml.Serialization.XmlArrayItemAttribute("category")]
        public System.Collections.ObjectModel.Collection<CategoryType> Categories
        {
            get
            {
                return this._categories;
            }
            private set
            {
                this._categories = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Categories collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoriesSpecified
        {
            get
            {
                return (this.Categories.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Test_SuiteType" /> class.</para>
        /// </summary>
        public Test_SuiteType()
        {
            this._categories = new System.Collections.ObjectModel.Collection<CategoryType>();
            this._properties = new System.Collections.ObjectModel.Collection<PropertyType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PropertyType> _properties;
        
        [System.Xml.Serialization.XmlArrayAttribute("properties")]
        [System.Xml.Serialization.XmlArrayItemAttribute("property")]
        public System.Collections.ObjectModel.Collection<PropertyType> Properties
        {
            get
            {
                return this._properties;
            }
            private set
            {
                this._properties = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Properties collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertiesSpecified
        {
            get
            {
                return (this.Properties.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("failure")]
        public FailureType Failure { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reason")]
        public ReasonType Reason { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("results")]
        public ResultsType Results { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("success")]
        public string Success { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("time")]
        public string Time { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("executed")]
        public string Executed { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("asserts")]
        public string Asserts { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("result")]
        public string Result { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("categoriesType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CategoriesType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CategoryType> _category;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("category")]
        public System.Collections.ObjectModel.Collection<CategoryType> Category
        {
            get
            {
                return this._category;
            }
            private set
            {
                this._category = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CategoriesType" /> class.</para>
        /// </summary>
        public CategoriesType()
        {
            this._category = new System.Collections.ObjectModel.Collection<CategoryType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("categoryType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CategoryType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("propertiesType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertiesType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PropertyType> _property;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public System.Collections.ObjectModel.Collection<PropertyType> Property
        {
            get
            {
                return this._property;
            }
            private set
            {
                this._property = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PropertiesType" /> class.</para>
        /// </summary>
        public PropertiesType()
        {
            this._property = new System.Collections.ObjectModel.Collection<PropertyType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("propertyType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("test-caseType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Test_CaseType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CategoryType> _categories;
        
        [System.Xml.Serialization.XmlArrayAttribute("categories")]
        [System.Xml.Serialization.XmlArrayItemAttribute("category")]
        public System.Collections.ObjectModel.Collection<CategoryType> Categories
        {
            get
            {
                return this._categories;
            }
            private set
            {
                this._categories = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Categories collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoriesSpecified
        {
            get
            {
                return (this.Categories.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Test_CaseType" /> class.</para>
        /// </summary>
        public Test_CaseType()
        {
            this._categories = new System.Collections.ObjectModel.Collection<CategoryType>();
            this._properties = new System.Collections.ObjectModel.Collection<PropertyType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PropertyType> _properties;
        
        [System.Xml.Serialization.XmlArrayAttribute("properties")]
        [System.Xml.Serialization.XmlArrayItemAttribute("property")]
        public System.Collections.ObjectModel.Collection<PropertyType> Properties
        {
            get
            {
                return this._properties;
            }
            private set
            {
                this._properties = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Properties collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertiesSpecified
        {
            get
            {
                return (this.Properties.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("failure")]
        public FailureType Failure { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reason")]
        public ReasonType Reason { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("success")]
        public string Success { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("time")]
        public string Time { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("executed")]
        public string Executed { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("asserts")]
        public string Asserts { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("result")]
        public string Result { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("environmentType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnvironmentType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("nunit-version")]
        public string Nunit_Version { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("clr-version")]
        public string Clr_Version { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("os-version")]
        public string Os_Version { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("platform")]
        public string Platform { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("cwd")]
        public string Cwd { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("machine-name")]
        public string Machine_Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("user")]
        public string User { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("user-domain")]
        public string User_Domain { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("culture-infoType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Culture_InfoType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("current-culture")]
        public string Current_Culture { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("current-uiculture")]
        public string Current_Uiculture { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.488.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("resultType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("test-results", Namespace="")]
    public partial class ResultType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("environment")]
        public EnvironmentType Environment { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("culture-info")]
        public Culture_InfoType Culture_Info { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("test-suite")]
        public Test_SuiteType Test_Suite { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("total")]
        public decimal Total { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("errors")]
        public decimal Errors { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("failures")]
        public decimal Failures { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("inconclusive")]
        public decimal Inconclusive { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("not-run")]
        public decimal Not_Run { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ignored")]
        public decimal Ignored { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("skipped")]
        public decimal Skipped { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("invalid")]
        public decimal Invalid { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("date")]
        public string Date { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("time")]
        public string Time { get; set; }
    }
}
